#define CHAR_BIT __ch2o_builtin_bits((char)0)
#define CHAR_MIN __ch2o_builtin_min((char)0)
#define CHAR_MAX __ch2o_builtin_max((char)0)
#define SCHAR_MIN __ch2o_builtin_min((signed char)0)
#define SCHAR_MAX __ch2o_builtin_max((signed char)0)
#define UCHAR_MAX __ch2o_builtin_max((unsigned char)0)
#define SHRT_MIN __ch2o_builtin_min((short)0)
#define SHRT_MAX __ch2o_builtin_max((short)0)
#define USHRT_MAX __ch2o_builtin_max((unsigned short)0)
#define INT_MIN __ch2o_builtin_min((int)0)
#define INT_MAX __ch2o_builtin_max((int)0)
#define UINT_MAX __ch2o_builtin_max((unsigned int)0)
#define LONG_MIN __ch2o_builtin_min((long)0)
#define LONG_MAX __ch2o_builtin_max((long)0)
#define ULONG_MAX __ch2o_builtin_max((unsigned lond)0)
#define LLONG_MIN __ch2o_builtin_min((long long)0)
#define LLONG_MAX __ch2o_builtin_max((long long)0)
#define ULLONG_MAX __ch2o_builtin_max((unsigned long long)0)
